// Code generated by go-pkgz/enum; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// AccountType represents account type (cloud/robot)
type AccountType = accountType

// String returns the string representation of AccountType
func (a AccountType) String() string {
	switch a {
	case AccountTypeCloud:
		return "cloud"
	case AccountTypeRobot:
		return "robot"
	}
	return fmt.Sprintf("AccountType(%d)", a)
}

// ParseAccountType parses a string into an AccountType
func ParseAccountType(s string) (AccountType, error) {
	switch strings.ToLower(s) {
	case "cloud":
		return AccountTypeCloud, nil
	case "robot":
		return AccountTypeRobot, nil
	}
	return 0, fmt.Errorf("invalid AccountType: %q", s)
}

// AllAccountTypes returns all valid AccountType values
func AllAccountTypes() []AccountType {
	return []AccountType{AccountTypeCloud, AccountTypeRobot}
}
