// Code generated by go-pkgz/enum; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// LogAction represents server log action
type LogAction = logAction

// String returns the string representation of LogAction
func (l LogAction) String() string {
	switch l {
	case LogActionAdded:
		return "added"
	case LogActionPaused:
		return "paused"
	case LogActionDeleted:
		return "deleted"
	case LogActionSynced:
		return "synced"
	case LogActionUpdated:
		return "updated"
	}
	return fmt.Sprintf("LogAction(%d)", l)
}

// ParseLogAction parses a string into a LogAction
func ParseLogAction(s string) (LogAction, error) {
	switch strings.ToLower(s) {
	case "added":
		return LogActionAdded, nil
	case "paused":
		return LogActionPaused, nil
	case "deleted":
		return LogActionDeleted, nil
	case "synced":
		return LogActionSynced, nil
	case "updated":
		return LogActionUpdated, nil
	}
	return 0, fmt.Errorf("invalid LogAction: %q", s)
}

// AllLogActions returns all valid LogAction values
func AllLogActions() []LogAction {
	return []LogAction{LogActionAdded, LogActionPaused, LogActionDeleted, LogActionSynced, LogActionUpdated}
}
