// Code generated by go-pkgz/enum; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// ProviderType represents cloud provider type
type ProviderType = providerType

// String returns the string representation of ProviderType
func (p ProviderType) String() string {
	switch p {
	case ProviderTypeHetzner:
		return "hetzner"
	case ProviderTypeAWS:
		return "aws"
	case ProviderTypeScaleway:
		return "scaleway"
	case ProviderTypeVsysHost:
		return "vsys_host"
	}
	return fmt.Sprintf("ProviderType(%d)", p)
}

// ParseProviderType parses a string into a ProviderType
func ParseProviderType(s string) (ProviderType, error) {
	switch strings.ToLower(s) {
	case "hetzner":
		return ProviderTypeHetzner, nil
	case "aws":
		return ProviderTypeAWS, nil
	case "scaleway":
		return ProviderTypeScaleway, nil
	case "vsys_host":
		return ProviderTypeVsysHost, nil
	}
	return 0, fmt.Errorf("invalid ProviderType: %q", s)
}

// AllProviderTypes returns all valid ProviderType values
func AllProviderTypes() []ProviderType {
	return []ProviderType{ProviderTypeHetzner, ProviderTypeAWS, ProviderTypeScaleway, ProviderTypeVsysHost}
}
