// Code generated by go-pkgz/enum; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// ServerType represents server type (cloud/robot)
type ServerType = serverType

// String returns the string representation of ServerType
func (s ServerType) String() string {
	switch s {
	case ServerTypeCloud:
		return "cloud"
	case ServerTypeRobot:
		return "robot"
	}
	return fmt.Sprintf("ServerType(%d)", s)
}

// ParseServerType parses a string into a ServerType
func ParseServerType(s string) (ServerType, error) {
	switch strings.ToLower(s) {
	case "cloud":
		return ServerTypeCloud, nil
	case "robot":
		return ServerTypeRobot, nil
	}
	return 0, fmt.Errorf("invalid ServerType: %q", s)
}

// AllServerTypes returns all valid ServerType values
func AllServerTypes() []ServerType {
	return []ServerType{ServerTypeCloud, ServerTypeRobot}
}
