// Code generated by go-pkgz/enum; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// ServerStatus represents server status
type ServerStatus = serverStatus

// String returns the string representation of ServerStatus
func (s ServerStatus) String() string {
	switch s {
	case ServerStatusActive:
		return "active"
	case ServerStatusPaused:
		return "paused"
	case ServerStatusDeleted:
		return "deleted"
	}
	return fmt.Sprintf("ServerStatus(%d)", s)
}

// ParseServerStatus parses a string into a ServerStatus
func ParseServerStatus(s string) (ServerStatus, error) {
	switch strings.ToLower(s) {
	case "active":
		return ServerStatusActive, nil
	case "paused":
		return ServerStatusPaused, nil
	case "deleted":
		return ServerStatusDeleted, nil
	}
	return 0, fmt.Errorf("invalid ServerStatus: %q", s)
}

// AllServerStatuses returns all valid ServerStatus values
func AllServerStatuses() []ServerStatus {
	return []ServerStatus{ServerStatusActive, ServerStatusPaused, ServerStatusDeleted}
}
