// Code generated by go-pkgz/enum; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// Theme represents UI theme
type Theme = theme

// String returns the string representation of Theme
func (t Theme) String() string {
	switch t {
	case ThemeSystem:
		return "system"
	case ThemeLight:
		return "light"
	case ThemeDark:
		return "dark"
	case ThemeDarkElectric:
		return "dark-electric"
	case ThemeDarkCyber:
		return "dark-cyber"
	}
	return fmt.Sprintf("Theme(%d)", t)
}

// ParseTheme parses a string into a Theme
func ParseTheme(s string) (Theme, error) {
	switch strings.ToLower(s) {
	case "", "system":
		return ThemeSystem, nil
	case "light":
		return ThemeLight, nil
	case "dark":
		return ThemeDark, nil
	case "dark-electric":
		return ThemeDarkElectric, nil
	case "dark-cyber":
		return ThemeDarkCyber, nil
	}
	return 0, fmt.Errorf("invalid Theme: %q", s)
}
