// Code generated by go-pkgz/enum; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// ViewMode represents UI view mode
type ViewMode = viewMode

// String returns the string representation of ViewMode
func (v ViewMode) String() string {
	switch v {
	case ViewModeTable:
		return "table"
	case ViewModeCards:
		return "cards"
	}
	return fmt.Sprintf("ViewMode(%d)", v)
}

// ParseViewMode parses a string into a ViewMode
func ParseViewMode(s string) (ViewMode, error) {
	switch strings.ToLower(s) {
	case "table":
		return ViewModeTable, nil
	case "cards":
		return ViewModeCards, nil
	}
	return 0, fmt.Errorf("invalid ViewMode: %q", s)
}
